<script setup>
import {ref,computed} from 'vue';
import {Store} from '../../../store';
import {isPaid,totalsFor,money,businessDate} from '../../../domain/pos';
import {usePdfGenerator} from '../../../composables/usePdfGenerator';
import Icon from '../../ui/EditionIcon.vue';
import SalesTable from './sales-parts/SalesTable.vue';
import SalesEditor from './sales-parts/SalesEditor.vue';
import Receipt from '../pos/EditionReceipt.vue';
const view=ref('list'),client=ref(''),txForm=ref({}),saving=ref(false),generating=ref(false),receipt=ref(null);
const {generatePdf}=usePdfGenerator();
const company=computed(()=>Store.state.selectedCompany||{}),clients=computed(()=>Store.state.clients),products=computed(()=>Store.state.products);
const prefs=computed(()=>({baseTheme:'clean',currency:'RM',labels:{invoice:'INVOICE',quote:'QUOTE',billTo:'Bill to'},showLogo:true,...company.value.preferences}));
const transactions=computed(()=>Store.state.transactions.filter(t=>!client.value||t.client_id===client.value));
const stats=computed(()=>{const invoice=transactions.value.filter(t=>t.type==='Invoice');return {paid:invoice.filter(isPaid).reduce((s,t)=>s+Number(t.total||0),0),due:invoice.filter(t=>!isPaid(t)&&t.status!=='Voided').reduce((s,t)=>s+Number(t.total||0),0),quotes:transactions.value.filter(t=>t.type==='Quote'&&t.status!=='Converted').length};});
const id=()=>crypto.randomUUID().replaceAll('-','').slice(0,20);
function newInvoice(type){const uuid=id();txForm.value={id:uuid,company_id:company.value.id,client_id:client.value,project:'',type:type==='quote'?'Quote':'Invoice',number:(type==='quote'?'QT-':'INV-')+uuid.toUpperCase(),date:businessDate(),status:'Pending',items:[{desc:'',unit:'Unit',qty:1,price:0}],taxRate:company.value.preferences?.taxRate??company.value.preferences?.tax??0,discount:0,notes:prefs.value.defaultNotes||'',_new:true};view.value='editor';}
function edit(tx){if(tx.source==='pos'){receipt.value=tx;return;}txForm.value=JSON.parse(JSON.stringify(tx));view.value='editor';}
async function save(){if(saving.value)return;if(txForm.value.type==='Quote'&&!txForm.value.client_id)return Store.notify('Choose a customer for this quote.','error');saving.value=true;try{if(!txForm.value.items.length||txForm.value.items.some(i=>!i.desc?.trim()))throw new Error('Add descriptions to every line item.');const {_new,...data}=txForm.value;Object.assign(data,totalsFor(data.items,data.taxRate||0,data.discount||0));if(_new)await Store.addTransaction(data);else await Store.updateTransaction(data);view.value='list';}catch(e){Store.notify(e.message,'error');}finally{saving.value=false;}}
async function remove(id){if(!confirm('Delete this document?'))return;try{await Store.deleteTransaction(id);Store.notify('Document deleted.');}catch(e){Store.notify(e.message,'error');}}
async function paid(tx){try{await Store.updateTransaction({...tx,status:'Paid'});}catch(e){Store.notify(e.message,'error');}}
async function convert(tx){try{await Store.financeModule.convertQuote(Store,tx);Store.notify('Quote converted to invoice.');}catch(e){Store.notify(e.message,'error');}}
async function download(tx){if(tx.source==='pos'){receipt.value=tx;return;}txForm.value=JSON.parse(JSON.stringify(tx));view.value='editor';generating.value=true;try{await generatePdf(tx,'invoice-print-area',`${tx.number}.pdf`);view.value='list';}catch(e){Store.notify(`PDF could not be created: ${e.message}`,'error');}finally{generating.value=false;}}
async function saveNotes(defaultNotes){try{await Store.updatePreferences({defaultNotes});Store.notify('Default notes saved.');}catch(e){Store.notify(e.message,'error');}}
</script>
<template><div class="ed-page"><template v-if="view==='list'"><header class="ed-page-head"><div><div class="ed-eyebrow">WORKSPACE / SALES</div><h1>Every sale, accounted for.</h1><p>Receipts, invoices and quotes, with a clear path to the details.</p></div><div class="ed-actions"><button class="ed-btn" @click="newInvoice('quote')">New quote</button><button class="ed-btn primary" @click="newInvoice('invoice')"><Icon name="plus" />New invoice</button></div></header><div class="ed-metrics ed-metrics-three"><div class="ed-metric"><label>Collected · all time</label><strong>{{ money(stats.paid,prefs.currency) }}</strong><small>Paid & cleared invoices</small></div><div class="ed-metric"><label>Awaiting payment</label><strong>{{ money(stats.due,prefs.currency) }}</strong><small>Outstanding invoices</small></div><div class="ed-metric"><label>Open quotes</label><strong>{{ stats.quotes }}</strong><small>Awaiting conversion</small></div></div><div class="ed-filters"><label class="ed-field" style="min-width:230px"><span>Customer</span><select v-model="client"><option value="">All customers</option><option v-for="c in clients" :key="c.id" :value="c.id">{{ c.name }}</option></select></label></div><SalesTable :transactions="transactions" :currency="prefs.currency" :clients="clients" @edit="edit" @delete="remove" @mark-paid="paid" @convert="convert" @download="download" @new-invoice="newInvoice" /></template><SalesEditor v-else :txForm="txForm" :activeCompany="company" :companyPrefs="prefs" :clients="clients" :products="products" :isGeneratingPdf="generating" :saving="saving" @save="save" @cancel="view='list'" @saveDefaultNotes="saveNotes"/><Receipt v-if="receipt" :sale="receipt" @close="receipt=null"/></div></template>
