import { chromium } from 'playwright';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
assert.equal(process.env.MYFIN_BROWSER_ACCEPTANCE,'myfin-phase05-20260913','Disposable Phase05 browser harness required');
const origin='http://localhost:8080';
const password=(await readFile('/run/seed','utf8')).trim();
const evidence='/evidence';await mkdir(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();page.setDefaultTimeout(15000);
const errors=[],checkpoints=[];
page.on('pageerror',e=>errors.push(e.message));
const suffix=Date.now().toString(36),companyName='Management shop '+suffix,managerName='Manager '+suffix,staffName='Teammate '+suffix;
const managerEmail=`manager-${suffix}@myfin.test`,staffEmail=`staff-${suffix}@myfin.test`;
const visibleDialog=()=>page.locator('dialog[open]');
const peopleSection=()=>page.locator('section').filter({has:page.getByRole('heading',{name:'People & access.',exact:true})});
const companiesSection=()=>page.locator('section').filter({has:page.getByRole('heading',{name:'A place for every business.',exact:true})});
async function shot(name){await page.screenshot({path:`${evidence}/${name}.png`,fullPage:true});checkpoints.push(name);console.log('passed: '+name);}
async function login(target,email){await target.goto(origin);await target.getByLabel('Email address').fill(email);await target.getByLabel('Password',{exact:true}).fill(password);await target.getByRole('button',{name:'Sign in to workspace'}).click();await target.getByRole('button',{name:'Sign out',exact:true}).waitFor();}
async function api(path){const r=await page.request.get(origin+'/api'+path);assert.equal(r.status(),200);return r.json();}
async function userRow(name){await peopleSection().getByLabel('Search people').fill(name);const row=peopleSection().locator('tbody tr').filter({hasText:name});await row.waitFor();assert.equal(await row.count(),1);return row;}
try {
  await login(page,'operator@myfin.test');
  await page.getByRole('heading',{name:'A place for every business.'}).waitFor();
  const before=(await api('/companies')).length;
  await companiesSection().getByRole('button',{name:'Enroll company',exact:true}).click();
  await visibleDialog().getByLabel(/^Company name/).fill(companyName);
  await visibleDialog().getByLabel('Registration number').fill('SYNTHETIC-05');
  await visibleDialog().getByLabel('Company email').fill('shop@myfin.test');
  await visibleDialog().getByLabel('Phone',{exact:true}).fill('0000000000');
  await visibleDialog().getByLabel('Business address').fill('Synthetic browser acceptance address');
  await visibleDialog().getByLabel('Default tax (%)').fill('6');
  await visibleDialog().getByLabel('Who will manage this company?').selectOption('new');
  await visibleDialog().getByLabel('Manager name *').fill(managerName);
  await visibleDialog().getByLabel('Manager email *').fill(managerEmail);
  await visibleDialog().getByLabel('Initial password *').fill(password);
  await visibleDialog().getByRole('button',{name:'Review details'}).click();
  await visibleDialog().getByRole('heading',{name:companyName,exact:true}).waitFor();
  await shot('management-enrollment-review');
  await visibleDialog().getByRole('button',{name:'Enroll company',exact:true}).click();
  await visibleDialog().getByRole('heading',{name:'Your company is ready'}).waitFor();
  await visibleDialog().getByRole('button',{name:'Done',exact:true}).click();
  await companiesSection().getByRole('heading',{name:companyName,exact:true}).waitFor();
  const companies=await api('/companies'),company=companies.find(c=>c.name===companyName);
  assert.equal(companies.length,before+1);assert.equal(company.preferences.taxRate,6);assert.equal(company.email,'shop@myfin.test');
  const manager=(await api('/users')).find(u=>u.email===managerEmail);assert.equal(manager.role,'company_admin');assert.equal(manager.company_id,company.id);
  await shot('management-company-directory');
  let interruptEnrollment=true;
  await page.route('**/api/companies/enroll',async route=>{
    if(interruptEnrollment){interruptEnrollment=false;const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');}
    else await route.continue();
  });
  const recoveryName='Enrollment recovery '+suffix;
  await companiesSection().getByRole('button',{name:'Enroll company',exact:true}).click();
  await visibleDialog().getByLabel(/^Company name/).fill(recoveryName);
  await visibleDialog().getByRole('button',{name:'Review details'}).click();
  await visibleDialog().getByRole('button',{name:'Enroll company',exact:true}).click();
  await visibleDialog().getByRole('button',{name:'Retry enrollment',exact:true}).waitFor();
  await page.keyboard.press('Escape');assert.equal(await visibleDialog().count(),1);
  assert.equal(await visibleDialog().getByRole('button',{name:'Close dialog',exact:true}).isDisabled(),true);
  await visibleDialog().getByRole('button',{name:'Retry enrollment',exact:true}).click();
  await visibleDialog().getByRole('heading',{name:'Your company is ready'}).waitFor();
  await visibleDialog().getByRole('button',{name:'Done',exact:true}).click();
  await page.unroute('**/api/companies/enroll');
  assert.equal((await api('/companies')).filter(c=>c.name===recoveryName).length,1);
  await shot('management-enrollment-response-recovery');
  await page.getByRole('button',{name:'People & access',exact:true}).click();
  await peopleSection().getByLabel(/^Role/).selectOption('company_admin');
  await peopleSection().getByLabel(/^Company/).selectOption(company.id);
  await userRow(managerName);
  await peopleSection().getByRole('button',{name:'Clear filters'}).click();
  await peopleSection().getByRole('button',{name:'Add teammate',exact:true}).click();
  await visibleDialog().getByLabel('Full name *').fill(staffName);
  await visibleDialog().getByLabel('Sign-in email *').fill(staffEmail);
  await visibleDialog().getByLabel('Initial password *').fill(password);
  await visibleDialog().getByLabel(/^Company \*/).selectOption(company.id);
  await visibleDialog().getByLabel('Full name *').press('Enter');
  await visibleDialog().waitFor({state:'hidden'});
  let row=await userRow(staffName);
  await row.getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await visibleDialog().getByLabel('Sign-in email *').getAttribute('readonly'),'');
  await visibleDialog().getByLabel('Full name *').fill(staffName+' updated');
  await visibleDialog().getByRole('button',{name:'Save teammate'}).click();
  await visibleDialog().waitFor({state:'hidden'});
  row=await userRow(staffName+' updated');
  const staffContext=await browser.newContext();const staffPage=await staffContext.newPage();await login(staffPage,staffEmail);
  assert.equal((await staffPage.request.get(origin+'/api/me')).status(),200);
  await row.getByRole('button',{name:'Suspend',exact:true}).click();
  await visibleDialog().getByRole('button',{name:'Suspend account',exact:true}).click();
  await visibleDialog().waitFor({state:'hidden'});await row.getByText('Suspended',{exact:true}).waitFor();
  assert.equal((await staffPage.request.get(origin+'/api/me')).status(),401);
  await row.getByRole('button',{name:'Edit',exact:true}).click();
  await visibleDialog().getByLabel('Full name *').fill(staffName+' suspended');
  await visibleDialog().getByRole('button',{name:'Save teammate'}).click();await visibleDialog().waitFor({state:'hidden'});
  row=await userRow(staffName+' suspended');await row.getByText('Suspended',{exact:true}).waitFor();
  await peopleSection().getByLabel(/^Status/).selectOption('disabled');assert.equal(await peopleSection().locator('tbody tr').count(),1);
  await shot('management-suspended-filter');
  await row.getByRole('button',{name:'Reactivate',exact:true}).click();await visibleDialog().getByRole('button',{name:'Reactivate account',exact:true}).click();await visibleDialog().waitFor({state:'hidden'});
  await peopleSection().getByLabel(/^Status/).selectOption('');row=await userRow(staffName+' suspended');await row.getByText('Active',{exact:true}).waitFor();
  const restored=(await api('/users')).find(u=>u.email===staffEmail);assert.equal(restored.company_id,company.id);assert.equal(restored.disabled,false);
  await staffContext.close();
  const freshStaffContext=await browser.newContext();const freshStaffPage=await freshStaffContext.newPage();await login(freshStaffPage,staffEmail);
  await row.getByRole('button',{name:'Sign out sessions',exact:true}).click();await visibleDialog().getByRole('button',{name:'Sign out sessions',exact:true}).click();await visibleDialog().waitFor({state:'hidden'});
  assert.equal((await freshStaffPage.request.get(origin+'/api/me')).status(),401);await freshStaffContext.close();
  row=await userRow(managerName);await row.getByRole('button',{name:'Suspend',exact:true}).click();await visibleDialog().getByRole('button',{name:'Suspend account',exact:true}).click();
  await visibleDialog().getByRole('alert').filter({hasText:'Assign another active manager'}).waitFor();await shot('management-last-manager-protection');await visibleDialog().getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Companies',exact:true}).click();await companiesSection().getByLabel('Search companies').fill(companyName);
  let tile=companiesSection().locator('article').filter({hasText:companyName});await tile.getByRole('button',{name:'Archive',exact:true}).click();await visibleDialog().getByRole('button',{name:'Archive company',exact:true}).click();await visibleDialog().waitFor({state:'hidden'});
  await companiesSection().getByLabel(/^Status/).selectOption('archived');tile=companiesSection().locator('article').filter({hasText:companyName});await tile.getByRole('heading',{name:companyName,exact:true}).waitFor();
  assert.equal((await api('/companies')).some(c=>c.id===company.id),false);assert.equal((await api('/users')).find(u=>u.id===manager.id).company_id,company.id);
  await shot('management-archived-company');
  await tile.getByRole('button',{name:'Restore company',exact:true}).click();await visibleDialog().getByText('Suspended accounts remain suspended.',{exact:false}).waitFor();await visibleDialog().getByRole('button',{name:'Restore company',exact:true}).click();await visibleDialog().waitFor({state:'hidden'});
  await companiesSection().getByLabel(/^Status/).selectOption('active');await companiesSection().getByRole('heading',{name:companyName,exact:true}).waitFor();
  assert.equal((await api('/companies')).some(c=>c.id===company.id),true);
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await shot('management-mobile-companies');
  await context.setOffline(true);await companiesSection().getByText('Connect to the internet to manage companies and enroll a new business.').waitFor();assert.equal(await companiesSection().getByRole('button',{name:'Enroll company',exact:true}).isDisabled(),true);await context.setOffline(false);
  await page.setViewportSize({width:1440,height:1000});
  await companiesSection().getByRole('button',{name:'Enroll company',exact:true}).click();await visibleDialog().waitFor();await page.keyboard.press('Escape');await visibleDialog().waitFor({state:'hidden'});assert.equal(await companiesSection().getByRole('button',{name:'Enroll company',exact:true}).evaluate(el=>el===document.activeElement),true);
  await tile.getByRole('button',{name:'Open workspace',exact:true}).click();await page.getByRole('link',{name:'Company profile',exact:true}).click();await page.getByRole('heading',{name:'Your company profile.'}).waitFor();await page.getByText('RM · 6% default tax',{exact:true}).waitFor();await shot('management-company-profile');
  const managerContext=await browser.newContext();const managerPage=await managerContext.newPage();await login(managerPage,managerEmail);await managerPage.getByRole('link',{name:'Team & access',exact:true}).click();await managerPage.getByRole('heading',{name:'People & access.'}).waitFor();assert.equal(await managerPage.getByRole('button',{name:'Enroll company',exact:true}).count(),0);assert.equal(await managerPage.getByRole('button',{name:'People & access',exact:true}).count(),0);await managerContext.close();
  assert.deepEqual(errors,[],'No browser runtime errors');
  await writeFile(evidence+'/management-browser-result.json',JSON.stringify({status:'passed',checkpoints,checks:['atomic company/new manager enrollment','directory role/company search','keyboard account creation','immutable email edit','suspend/revoke active session','disabled state preserved on edit','reactivate retains assignment','last manager error','archive/restore retains members','mobile width','offline actions disabled','Escape restores focus','company profile tax consistency','company manager scoped UI'],runtimeErrors:errors},null,2)+'\n');
} catch(e) {
  await page.screenshot({path:evidence+'/management-failure.png',fullPage:true});
  console.error('Management browser acceptance failed:',e.message);console.error('Runtime error count:',errors.length);process.exitCode=1;
} finally {await browser.close();}
