import test from 'node:test';
import assert from 'node:assert/strict';
import { cents, totalsFor, roundToFiveSen, checkoutTotalsFor, saleTotalsFor, normalizeProduct, cartItem, createSale, deductItems, isPaid, businessDate } from '../src/domain/pos.js';
const company={id:'shop',name:'Shop',preferences:{tax:6,currency:'RM'}},user={uid:'cashier',username:'Cashier'};
const product=normalizeProduct({id:'coffee',name:'Coffee',sku:'COF-1',price:0.1,stock:3,trackStock:true});
test('currency rounds at line and tax boundaries',()=>{const totals=totalsFor([{qty:3,price:0.1}],6);assert.equal(totals.total,0.32);assert.equal(totals.tax,0.02);assert.equal(cents(36.5),3650);});
test('Malaysian counter rounding covers every sen ending without changing ordinary document totals',()=>{
 const expected=[[19.90,0,19.90],[19.91,-.01,19.90],[19.92,-.02,19.90],[19.93,.02,19.95],[19.94,.01,19.95],[19.95,0,19.95],[19.96,-.01,19.95],[19.97,-.02,19.95],[19.98,.02,20],[19.99,.01,20]];
 for(const [before,rounding,total] of expected)assert.deepEqual(roundToFiveSen(before),{totalBeforeRounding:before,rounding,total});
 assert.equal(totalsFor([{qty:1,price:19.93}]).total,19.93);assert.deepEqual(checkoutTotalsFor([{qty:1,price:19.93}]),{subtotal:19.93,discountAmount:0,tax:0,totalBeforeRounding:19.93,rounding:.02,total:19.95,taxRate:0,discount:0});
 const items=[{qty:1,price:19.93}],rounded={schemaVersion:3,items,taxRate:0,discount:0,totalBeforeRounding:19.93,rounding:.02};assert.equal(saleTotalsFor(rounded).total,19.95);assert.equal(saleTotalsFor({schemaVersion:2,items,taxRate:0,discount:0}).total,19.93);assert.throws(()=>saleTotalsFor({...rounded,rounding:undefined}),/required/);assert.throws(()=>saleTotalsFor({schemaVersion:2,items,taxRate:0,discount:0,rounding:0}),/Legacy/);
});
test('displayed exact cash is accepted; rounded tender and change persist',()=>{const sale=createSale({id:'stable',items:[cartItem(product)],company,user,method:'Cash',received:0.10});assert.equal(sale.schemaVersion,3);assert.equal(sale.totalBeforeRounding,0.11);assert.equal(sale.rounding,-0.01);assert.equal(sale.total,0.10);assert.equal(sale.change,0);assert.equal(sale.received,0.10);assert.equal(sale.items[0].productId,'coffee');assert.equal(sale.storeSnapshot.name,'Shop');for(const method of ['QR Pay','Card']){const external=createSale({id:method.replace(' ',''),items:[cartItem(product)],company,user,method,confirmed:true});assert.equal(external.total,0.10);assert.equal(external.received,0.10);assert.equal(external.change,0);}});
test('invalid tender, quantity and external confirmation are rejected',()=>{for(const received of [0,-1,NaN])assert.throws(()=>createSale({id:'x',items:[cartItem(product)],company,user,method:'Cash',received}));assert.throws(()=>totalsFor([{price:1,qty:0}]));assert.throws(()=>createSale({id:'x',items:[cartItem(product)],company,user,method:'Card',received:1,confirmed:false}));});
test('legacy SKU, tax, variants and service stock adapt without data migration',()=>{const p=normalizeProduct({id:'v',code:'OLD',category:'Retail',variants:[{name:'Blue',price:10,stock:2}]});assert.equal(p.sku,'OLD');assert.equal(p.variants[0].id,'legacy-0');assert.equal(cartItem(p,p.variants[0]).variantId,'legacy-0');assert.equal(normalizeProduct({name:'Service',category:'Service',stock:0}).trackStock,false);assert.equal(normalizeProduct({name:'Uncounted'}).trackStock,false);});
test('deduction aggregates quantities, isolates variants and rejects overselling',()=>{const p=normalizeProduct({id:'v',name:'Cup',trackStock:true,variants:[{id:'a',name:'A',price:10,stock:2},{id:'b',name:'B',price:10,stock:4}]});const result=deductItems([p],[{...cartItem(p,p.variants[0]),qty:2}]);assert.equal(result.updates[0].variants[0].stock,0);assert.equal(result.updates[0].variants[1].stock,4);assert.equal(p.variants[0].stock,2);assert.throws(()=>deductItems([product],[{...cartItem(product),qty:4}]));});
test('accepted offline sale preserves stock shortage for review',()=>{const result=deductItems([product],[{...cartItem(product),qty:4}],true);assert.equal(result.updates[0].stock,-1);assert.equal(result.shortage,true);});
test('reports agree on legacy paid statuses and Malaysian dates',()=>{assert.ok(isPaid({type:'Invoice',status:'Cleared'}));assert.ok(isPaid({type:'Invoice',status:'Paid'}));assert.equal(isPaid({type:'Quote',status:'Paid'}),false);assert.equal(businessDate('2026-09-09T18:00:00Z'),'2026-09-10');assert.equal(businessDate('2026-09-09'),'2026-09-09');});
