<script setup>
import { computed, onBeforeUnmount } from 'vue';
import Modal from '../../ui/EditionModal.vue';
import Icon from '../../ui/EditionIcon.vue';
import { Store } from '../../../store';
import { money } from '../../../domain/pos';
const props=defineProps({sale:Object});defineEmits(['close']);
const store=computed(()=>props.sale.storeSnapshot||{...Store.state.selectedCompany,currency:Store.state.selectedCompany?.preferences?.currency||'RM',footer:Store.state.selectedCompany?.preferences?.receiptFooter||'Thank you for shopping with us.'});
const currency=computed(()=>store.value.currency||'RM');
function cleanup(){document.body.classList.remove('ed-print-receipt');document.body.style.removeProperty('--receipt-width');}
function print(){document.body.style.setProperty('--receipt-width',store.value.paperWidth==='58'?'58mm':'80mm');document.body.classList.add('ed-print-receipt');window.addEventListener('afterprint',cleanup,{once:true});window.print();}
onBeforeUnmount(cleanup);
</script>
<template><Modal title="Receipt preview" @close="$emit('close')"><article class="ed-receipt"><header><h3>{{ store.name }}</h3><small v-if="store.registration">{{ store.registration }}</small><small>{{ store.address }}</small><small>{{ store.phone }}</small></header><div class="ed-receipt-number">{{ sale.number }}</div><small>{{ new Date(sale.date).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}) }}</small><small>Cashier: {{ sale.cashierName || sale.history?.[0]?.user || '—' }}</small><small>{{ sale.customerName || Store.state.clients.find(c=>c.id===sale.client_id)?.name || 'Walk-in customer' }}</small><div v-if="sale.syncStatus==='pending' || Store.state.pendingSales.some(s=>s.id===sale.id)" class="ed-notice warning">Saved on this device · Awaiting cloud sync</div><div v-for="(item,i) in sale.items||[]" :key="i" class="ed-receipt-line"><div>{{ item.desc || item.name }}<small>{{ item.qty }} × {{ money(item.price,currency) }}</small></div><span>{{ money(Math.round(Number(item.qty)*Number(item.price)*100)/100,currency) }}</span></div><div class="ed-summary"><span>Subtotal</span><span>{{ money(sale.subtotal??sale.total,currency) }}</span></div><div v-if="sale.discountAmount" class="ed-summary"><span>Discount</span><span>− {{ money(sale.discountAmount,currency) }}</span></div><div v-if="sale.tax" class="ed-summary"><span>Tax {{ sale.taxRate }}%</span><span>{{ money(sale.tax,currency) }}</span></div><div class="ed-summary total"><span>TOTAL</span><span>{{ money(sale.total,currency) }}</span></div><div class="ed-summary"><span>Payment</span><span>{{ sale.paymentMethod || 'Recorded payment' }}</span></div><template v-if="sale.received!=null"><div class="ed-summary"><span>Received</span><span>{{ money(sale.received,currency) }}</span></div><div class="ed-summary"><span>Change</span><span>{{ money(sale.change,currency) }}</span></div></template><footer>{{ store.footer }}</footer></article><template #actions><button class="ed-btn" @click="$emit('close')">Close</button><button class="ed-btn primary" @click="print"><Icon name="printer" />Print receipt</button></template></Modal></template>
