<script setup>
import {computed,ref,watch,onBeforeUnmount} from 'vue';
import {Store} from '../../store';
import {api,companyPath} from '../../services/api';
import {businessDate,money} from '../../domain/pos';
const report=ref(null),loading=ref(false),error=ref('');
let generation=0;
const currency=computed(()=>Store.state.selectedCompany?.preferences?.currency||'RM');
const today=computed(()=>report.value?.daily.find(d=>d.date===businessDate())||null);
const chart=computed(()=>{const days=report.value?.daily||[],max=Math.max(1,...days.map(d=>Math.abs(d.cashSurplus)));return days.map(d=>({...d,height:Math.abs(d.cashSurplus)/max*100}));});
async function refresh(){const request=++generation;report.value=null;error.value='';if(!Store.can('financialReports')||!Store.state.online||!Store.state.selectedCompany)return;loading.value=true;try{const value=await api(companyPath(Store,'/reports/summary'));if(request===generation&&Store.can('financialReports')&&Store.state.online)report.value=value;}catch(e){if(request===generation)error.value='The financial report could not be loaded. Reconnect and retry.';}finally{if(request===generation)loading.value=false;}}
watch(()=>[Store.state.selectedCompany?.id,Store.state.currentUser?.role,Store.state.online],refresh,{immediate:true});
onBeforeUnmount(()=>generation++);
</script>
<template><div v-if="Store.can('financialReports')&&Store.state.online" class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">OWNER / FINANCIAL REPORTS</div><h1>Recorded cash, clearly.</h1><p>POS receipts and recorded invoice payments, including partial payments, against recorded expenses.</p></div><button class="ed-btn" :disabled="loading" @click="refresh">{{ loading?'Loading…':'Refresh report' }}</button></header><p v-if="error" class="ed-alert" role="alert">{{ error }}</p><p v-if="loading" class="ed-notice" role="status">Loading the current financial report…</p><template v-if="report"><p class="ed-muted">{{ report.from }} to {{ report.to }} · Kuala Lumpur dates</p><div class="ed-metrics ed-metrics-three"><div class="ed-metric"><label>Collected today</label><strong>{{ money(today?.collected||0,currency) }}</strong><small>Recorded payments received today</small></div><div class="ed-metric"><label>Expenses today</label><strong>{{ money(today?.expenses||0,currency) }}</strong><small>Recorded business outgoings</small></div><div class="ed-metric"><label>Cash surplus today</label><strong>{{ money(today?.cashSurplus||0,currency) }}</strong><small>Collected payments less expenses</small></div></div><section><div class="ed-section-head"><h2>Daily cash surplus.</h2></div><div class="ed-surplus-chart" role="img" :aria-label="chart.map(d=>d.date+': '+money(d.cashSurplus,currency)).join('; ')"><div v-for="bar in chart" :key="bar.date" class="ed-surplus-column"><div class="ed-surplus-plot"><div class="ed-surplus-bar" :style="{height:Math.max(.5,bar.height/2)+'%',top:bar.cashSurplus<0?'50%':(50-bar.height/2)+'%',background:bar.cashSurplus<0?'#b97459':'var(--ed-accent)'}"></div></div><strong>{{ bar.date.slice(5) }}</strong><small>{{ money(bar.cashSurplus,currency) }}</small></div></div></section><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Date</th><th>Collected</th><th>Expenses</th><th>Cash surplus</th></tr></thead><tbody><tr v-for="day in report.daily" :key="day.date"><td>{{ day.date }}</td><td>{{ money(day.collected,currency) }}</td><td>{{ money(day.expenses,currency) }}</td><td>{{ money(day.cashSurplus,currency) }}</td></tr></tbody><tfoot><tr><th>Period total</th><td>{{ money(report.collected,currency) }}</td><td>{{ money(report.expenses,currency) }}</td><td>{{ money(report.cashSurplus,currency) }}</td></tr></tfoot></table></div><p class="ed-muted">{{ report.basis }} Cash surplus excludes inventory valuation and is not net profit. MyFin records payments; merchant devices confirm card and QR collections.</p></template></div><div v-else class="ed-notice">Connect with an authorized owner account to view financial reports.</div></template>
