<script setup>
import {ref,computed} from 'vue';
import {Store} from '../../store';
import Modal from '../ui/EditionModal.vue';
import {validEmail} from '../../domain/inventoryCsv';
const search=ref(''),form=ref(null),busy=ref(false),deleting=ref(null),error=ref('');
const clients=computed(()=>Store.state.clients.filter(c=>(Store.can('suppliersRead')||c.type!=='Supplier')&&[c.name,c.email,c.phone].join(' ').toLowerCase().includes(search.value.toLowerCase())));
function edit(client){if(client&&!Store.can('clientsWrite'))return;form.value=client?JSON.parse(JSON.stringify(client)):{name:'',email:'',phone:'',type:'Client'};error.value='';}
async function save(){if(busy.value)return;error.value='';try{form.value.name=form.value.name.trim();form.value.email=(form.value.email||'').trim();if(!form.value.name)throw new Error('Name is required.');if(!validEmail(form.value.email))throw new Error('Enter a valid email address.');busy.value=true;await Store.addClient(form.value);form.value=null;Store.notify('Contact saved.');}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function remove(){busy.value=true;try{await Store.deleteClient(deleting.value.id);deleting.value=null;Store.notify('Contact deleted.');}catch(e){Store.notify(e.message,'error');}finally{busy.value=false;}}
</script>
<template><div class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">CUSTOMER DIRECTORY</div><h1>Keep in touch.</h1><p>Customer details and emails for receipts.</p></div><button class="ed-btn primary" @click="edit()">+ New contact</button></header>
<div class="ed-filters"><input v-model="search" class="ed-input" aria-label="Search contacts" placeholder="Search name, phone or email"></div>
<div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Name</th><th>Type</th><th>Email</th><th>Phone</th><th>Actions</th></tr></thead><tbody><tr v-for="c in clients" :key="c.id"><td><strong>{{ c.name }}</strong></td><td>{{ c.type==='Supplier'?'Supplier':'Customer' }}</td><td>{{ c.email||'—' }}</td><td>{{ c.phone||'—' }}</td><td><div class="ed-actions"><button v-if="Store.can('clientsWrite')" class="ed-btn" :aria-label="`Edit ${c.name}`" @click="edit(c)">Edit</button><button v-if="Store.can('clientsWrite')" class="ed-btn danger" :aria-label="`Delete ${c.name}`" @click="deleting=c">Delete</button></div></td></tr><tr v-if="!clients.length"><td colspan="5" class="ed-empty">No matching contacts.</td></tr></tbody></table></div>
<Modal v-if="form" :title="form.id?'Edit contact':'New contact'" :busy="busy" @close="form=null"><form id="contact-editor" @submit.prevent="save"><fieldset :disabled="busy" class="ed-form-grid"><label class="ed-field wide"><span>Name *</span><input v-model="form.name" required maxlength="120" autocomplete="name"></label><label class="ed-field wide"><span>Email</span><input v-model.trim="form.email" type="email" maxlength="254" autocomplete="email" inputmode="email"></label><label class="ed-field"><span>Phone</span><input v-model="form.phone" type="tel" maxlength="40" autocomplete="tel"></label><label v-if="Store.can('suppliersWrite')" class="ed-field"><span>Contact type</span><select v-model="form.type"><option value="Client">Customer</option><option value="Supplier">Supplier</option></select></label></fieldset><p v-if="error" role="alert" class="ed-alert">{{ error }}</p></form><template #actions><button class="ed-btn" :disabled="busy" @click="form=null">Cancel</button><button class="ed-btn primary" form="contact-editor" type="submit" :disabled="busy">{{ busy?'Saving…':'Save contact' }}</button></template></Modal>
<Modal v-if="deleting" title="Delete contact?" :busy="busy" @close="deleting=null"><p>Delete {{ deleting.name }} from your directory?</p><template #actions><button class="ed-btn" :disabled="busy" @click="deleting=null">Cancel</button><button class="ed-btn danger" :disabled="busy" @click="remove">Delete contact</button></template></Modal>
</div></template>
