<script setup>
import {ref,computed} from 'vue';import {Store} from '../../store';import {useStorage} from '../../composables/useStorage';import {expenseRecords,money,businessDate} from '../../domain/pos';import Icon from '../ui/EditionIcon.vue';import Modal from '../ui/EditionModal.vue';
const {uploadFile,removeFile}=useStorage();
const search=ref(''),form=ref(null),file=ref(null),busy=ref(false),error=ref(''),deleting=ref(null);
const currency=computed(()=>Store.state.selectedCompany?.preferences?.currency||'RM');
const expenses=computed(()=>expenseRecords(Store.state).filter(e=>[e.description,e.category,e.payee].join(' ').toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>String(b.date).localeCompare(String(a.date))));
const total=computed(()=>expenses.value.reduce((s,e)=>s+Number(e.amount||0),0));
function edit(e){form.value=e?JSON.parse(JSON.stringify(e)):{description:'',amount:'',date:businessDate(),category:'General',payee:'',receiptUrl:'',receiptPath:''};file.value=null;error.value='';}
function pick(e){const chosen=e.target.files[0];if(chosen&&chosen.size>5*1024*1024){error.value='Choose a receipt smaller than 5 MB.';e.target.value='';return;}file.value=chosen;}
async function save(){if(busy.value)return;error.value='';if(!form.value.description.trim()||!Number.isFinite(Number(form.value.amount))||Number(form.value.amount)<=0){error.value='Enter a description and an amount greater than zero.';return;}busy.value=true;let uploaded=null;const oldPath=form.value.receiptPath;try{if(file.value)uploaded=await uploadFile(file.value,`receipts/${Store.state.selectedCompany.id}/${crypto.randomUUID()}_${file.value.name}`);const {origin,...data}=form.value;data.amount=Math.round(Number(data.amount)*100)/100;if(uploaded){data.receiptUrl=uploaded.url;data.receiptPath=uploaded.path;}if(origin==='transactions')await Store.updateTransaction({...data,total:data.amount});else await Store.addExpense(data);if(uploaded&&oldPath&&oldPath!==uploaded.path)await removeFile(oldPath);form.value=null;Store.notify('Expense saved.');}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function remove(){busy.value=true;try{if(deleting.value.origin==='transactions')await Store.deleteTransaction(deleting.value.id);else await Store.deleteExpense(deleting.value.id);if(deleting.value.receiptPath)await removeFile(deleting.value.receiptPath);Store.logActivity('Delete expense',deleting.value.description);deleting.value=null;Store.notify('Expense deleted.');}catch(e){Store.notify(e.message,'error');}finally{busy.value=false;}}
function exportCsv(){const rows=[['Date','Description','Category','Payee','Amount'],...expenses.value.map(e=>[e.date,e.description,e.category,e.payee,e.amount])];const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='myfin-expenses.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
</script>
<template><div class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">WORKSPACE / EXPENSES</div><h1>Keep the outgoings in view.</h1><p>Track what you spend, and keep the receipt close.</p></div><div class="ed-actions"><button class="ed-btn" @click="exportCsv"><Icon name="download" />Export</button><button class="ed-btn primary" @click="edit()"><Icon name="plus" />Record expense</button></div></header><div class="ed-filters"><div class="ed-search"><Icon name="search"/><input v-model="search" class="ed-input" aria-label="Search expenses" placeholder="Search description, category or payee"></div><div style="text-align:right"><div class="ed-eyebrow">TOTAL SHOWN</div><strong style="font-size:23px;font-weight:500">{{ money(total,currency) }}</strong></div></div><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Expense</th><th>Category</th><th>Payee</th><th>Date</th><th class="num">Amount</th><th>Receipt</th><th>Actions</th></tr></thead><tbody><tr v-for="e in expenses" :key="e.origin+e.id"><td><button class="ed-link" @click="edit(e)">{{ e.description }}</button><small v-if="e.origin==='transactions'">Legacy {{ e.type.toLowerCase() }}</small></td><td><span class="ed-pill">{{ e.category||'General' }}</span></td><td>{{ e.payee||'—' }}</td><td>{{ businessDate(e.date) }}</td><td class="num">{{ money(e.amount,currency) }}</td><td><a v-if="e.receiptUrl" class="ed-link" :href="e.receiptUrl" target="_blank" rel="noopener">View ↗</a><span v-else class="ed-muted">—</span></td><td><button class="ed-icon-button" :aria-label="`Edit ${e.description}`" @click="edit(e)"><Icon name="edit" /></button><button v-if="Store.canDelete()" class="ed-icon-button" :aria-label="`Delete ${e.description}`" @click="deleting=e"><Icon name="close" /></button></td></tr></tbody></table></div><div v-if="!expenses.length" class="ed-empty"><Icon name="wallet"/><h3>No expenses here yet.</h3><p>Add an expense or try a different search.</p></div>
<Modal v-if="form" :title="form.id?'Edit expense':'Record an expense'" :busy="busy" @close="form=null"><form id="expense-form" class="ed-form-grid" @submit.prevent="save"><label class="ed-field wide"><span>Description</span><input v-model="form.description" required></label><label class="ed-field"><span>Amount ({{ currency }})</span><input v-model="form.amount" type="number" step="0.01" min="0.01" required></label><label class="ed-field"><span>Date</span><input v-model="form.date" type="date" required></label><label class="ed-field"><span>Category</span><select v-model="form.category"><option v-for="c in ['General','Inventory','Operations','Utilities','Rent','Salaries','Equipment','Marketing','Software/SaaS','Travel']" :key="c">{{ c }}</option></select></label><label class="ed-field"><span>Paid to</span><input v-model="form.payee"></label><label class="ed-field wide"><span>Receipt · optional, up to 5 MB</span><input type="file" accept="image/*,application/pdf" @change="pick"><small v-if="form.receiptUrl&&!file" class="ed-muted">A receipt is attached. Upload a file to replace it.</small></label></form><p v-if="error" class="ed-alert" role="alert">{{ error }}</p><template #actions><button class="ed-btn" :disabled="busy" @click="form=null">Cancel</button><button class="ed-btn primary" :disabled="busy" type="submit" form="expense-form">{{ busy?'Saving…':'Save expense' }}</button></template></Modal><Modal v-if="deleting" title="Delete this expense?" :busy="busy" @close="deleting=null"><p>{{ deleting.description }} · {{ money(deleting.amount,currency) }}</p><template #actions><button class="ed-btn" :disabled="busy" @click="deleting=null">Keep expense</button><button class="ed-btn danger" :disabled="busy" @click="remove">Delete expense</button></template></Modal></div></template>
