<script setup>
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue';
import { Store } from '../../store';
import { money, cartItem, totalsFor, createSale, isPaid } from '../../domain/pos';
import { localPos } from '../../services/posLocal';
import Icon from '../ui/EditionIcon.vue';
import Modal from '../ui/EditionModal.vue';
import Receipt from './pos/EditionReceipt.vue';
// Each browser tab owns a cart; different tills still share the durable receipt outbox.
let registerId;
try { registerId=sessionStorage.getItem('myfin-register'); if(!registerId){registerId=crypto.randomUUID();sessionStorage.setItem('myfin-register',registerId);} } catch { registerId='default'; }
const uid=Store.state.currentUser.uid,companyId=Store.state.selectedCompany.id,draftKey=`${uid}:${companyId}:${registerId}`;
const newId=()=>crypto.randomUUID().replaceAll('-','').slice(0,20);
const cart=ref([]),held=ref([]),customerId=ref(''),saleId=ref(newId()),ready=ref(false),storageError=ref('');
const search=ref(''),category=ref('All items'),modal=ref(''),variantProduct=ref(null),holdName=ref(''),busy=ref(false),error=ref(''),lastSale=ref(null),receipt=ref(null);
const method=ref('Cash'),received=ref(''),confirmed=ref(false),productSearch=ref(null),cartPanel=ref(null);
const company=computed(()=>Store.state.selectedCompany||{}),currency=computed(()=>company.value.preferences?.currency||'RM');
const products=computed(()=>Store.state.products),clients=computed(()=>Store.state.clients.filter(c=>c.type!=='Supplier'));
const categories=computed(()=>['All items',...new Set(products.value.map(p=>p.category||'Other'))]);
const filtered=computed(()=>products.value.filter(p=>(category.value==='All items'||(p.category||'Other')===category.value)&&[p.name,p.sku,p.code,...p.variants.map(v=>v.name)].join(' ').toLowerCase().includes(search.value.toLowerCase())));
const totals=computed(()=>{try{return totalsFor(cart.value,company.value.preferences?.taxRate??company.value.preferences?.tax??0)}catch{return {subtotal:0,tax:0,total:0}}});
const count=computed(()=>cart.value.reduce((s,i)=>s+Number(i.qty),0));
const change=computed(()=>Math.max(0,Math.round((Number(received.value||0)-totals.value.total)*100)/100));
const recent=computed(()=>{const map=new Map();[...Store.state.transactions.filter(isPaid),...Store.state.pendingSales.map(s=>({...s,syncStatus:'pending'}))].forEach(s=>map.set(s.id,s));return [...map.values()].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,30);});
function draft(){return {cart:cart.value,held:held.value,customerId:customerId.value,saleId:saleId.value};}
async function persist(){if(!ready.value||busy.value)return;try{await localPos.saveDraft(draftKey,draft());storageError.value='';}catch{storageError.value='This device could not save the order. Enable browser storage or free some space before taking payment.';}}
watch([cart,held,customerId,saleId],persist,{deep:true});
onMounted(async()=>{try{const saved=await localPos.getDraft(draftKey);if(saved){cart.value=saved.cart||[];held.value=saved.held||[];customerId.value=saved.customerId||'';saleId.value=saved.saleId||newId();}await localPos.saveDraft(draftKey,draft());ready.value=true;}catch{storageError.value='Device storage is unavailable. Enable browser storage to use checkout.';}window.addEventListener('keydown',shortcut);});
onBeforeUnmount(()=>window.removeEventListener('keydown',shortcut));
function available(product,variant){const pending=Store.state.pendingSales.reduce((s,t)=>s+t.items.filter(i=>i.productId===product.id&&i.variantId===(variant?.id||'')).reduce((n,i)=>n+Number(i.qty),0),0);return (variant?.stock??product.stock)-pending;}
function quantityInCart(product,variant){return cart.value.filter(i=>i.productId===product.id&&i.variantId===(variant?.id||'')).reduce((s,i)=>s+Number(i.qty),0);}
function add(product,variant){if(!ready.value||busy.value)return;if(product.variants.length&&!variant){variantProduct.value=product;modal.value='variant';return;}if(product.trackStock&&quantityInCart(product,variant)+1>available(product,variant)){Store.notify('No more stock available for this item.','error');return;}const item=cartItem(product,variant);const existing=cart.value.find(i=>i.productId===item.productId&&i.variantId===item.variantId);if(existing)existing.qty++;else cart.value.push(item);modal.value='';}
function updateQty(index,value){const item=cart.value[index],q=Number(value),product=products.value.find(p=>p.id===item.productId),variant=product?.variants.find(v=>v.id===item.variantId);if(!Number.isFinite(q)||q<=0){cart.value.splice(index,1);return;}if(product?.trackStock&&q>available(product,variant)){Store.notify('That quantity exceeds available stock.','error');return;}item.qty=Math.round(q*1000)/1000;}
function openPayment(){error.value='';if(!ready.value||storageError.value||!cart.value.length)return;for(const item of cart.value){const p=products.value.find(p=>p.id===item.productId),v=p?.variants.find(v=>v.id===item.variantId);if(!p||(item.variantId&&!v))return Store.notify(`${item.desc} is no longer available. Remove it and choose a current item.`,'error');if(p.trackStock&&item.qty>available(p,v))return Store.notify(`${item.desc}: review available stock before payment.`,'error');}method.value='Cash';received.value='';confirmed.value=false;modal.value='payment';}
async function complete(){if(busy.value)return;error.value='';try{const sale=createSale({id:saleId.value,items:cart.value,company:company.value,user:Store.state.currentUser,method:method.value,received:received.value,confirmed:confirmed.value,customer:clients.value.find(c=>c.id===customerId.value),offline:!Store.state.online||Store.state.fromCache});busy.value=true;const next={cart:[],held:held.value,customerId:'',saleId:newId()};const saved=await Store.completeSale(sale,draftKey,next);lastSale.value=saved;cart.value=[];customerId.value='';saleId.value=next.saleId;modal.value='success';}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function hold(){held.value.push({id:newId(),name:holdName.value.trim()||`Order ${held.value.length+1}`,items:JSON.parse(JSON.stringify(cart.value)),customerId:customerId.value,saleId:saleId.value,total:totals.value.total,date:new Date().toISOString()});cart.value=[];customerId.value='';saleId.value=newId();modal.value='';await persist();Store.notify('Order held on this device.');}
function restore(index){const order=held.value[index];if(cart.value.length)held.value.push({id:newId(),name:'Previous cart',items:JSON.parse(JSON.stringify(cart.value)),customerId:customerId.value,saleId:saleId.value,total:totals.value.total,date:new Date().toISOString()});cart.value=order.items;customerId.value=order.customerId;saleId.value=order.saleId;held.value.splice(index,1);modal.value='';}
function shortcut(e){if(modal.value||receipt.value)return;if(e.key==='F2'){e.preventDefault();productSearch.value?.focus();}if(e.key==='F8'){e.preventDefault();openPayment();}}
function viewCart(){cartPanel.value?.scrollIntoView({behavior:Store.state.preferences.reduceMotion?'instant':'smooth',block:'start'});}
</script>
<template><div class="ed-page ed-pos-page"><header class="ed-page-head"><div><div class="ed-eyebrow">POINT OF SALE / {{ company.name }}</div><h1>Make someone's day.</h1><p>A good checkout should feel effortless.</p></div><div class="ed-actions"><button class="ed-btn" @click="modal='held'"><Icon name="clock" />Held orders<span v-if="held.length" class="ed-pill">{{ held.length }}</span></button><button class="ed-btn" @click="modal='recent'"><Icon name="receipt" />Recent sales</button></div></header>
<div v-if="storageError" class="ed-notice error" role="alert">{{ storageError }}</div><div v-if="!Store.state.online||Store.state.fromCache" class="ed-notice warning"><Icon name="cloud" /><div><strong>Working offline</strong>Orders and receipts save on this device and sync after reconnecting. Other tills may have sold stock since your last connection. Confirm QR/card payments using the merchant device's own connection.</div></div>
<div class="ed-pos-layout"><section><div class="ed-search" style="margin-bottom:15px"><Icon name="search" /><input ref="productSearch" v-model="search" class="ed-input" aria-label="Search products" placeholder="Search by product name or SKU · F2"></div><div class="ed-tabs"><button v-for="c in categories" :key="c" :class="{active:category===c}" :aria-pressed="category===c" @click="category=c">{{ c }}</button></div><div v-if="filtered.length" class="ed-product-grid"><button v-for="p in filtered" :key="p.id" class="ed-product" :aria-label="`Add ${p.name}`" :disabled="!ready||busy||(p.trackStock&&(p.variants.length?p.variants.every(v=>available(p,v)<=0):available(p)<=0))" @click="add(p)"><span class="ed-product-symbol"><Icon :name="p.category==='Service'?'clock':'box'" /></span><span v-if="p.trackStock&&!p.variants.length&&available(p)<5" class="ed-stock-label">{{ Math.max(0,available(p)) }} left</span><div><strong>{{ p.name }}</strong><small>{{ p.variants.length?`${p.variants.length} options`:p.sku||'No SKU' }} · {{ p.unit }}</small></div><div class="ed-product-footer"><span>{{ p.variants.length?'From ':'' }}{{ money(p.variants.length?Math.min(...p.variants.map(v=>v.price)):p.price,currency) }}</span><Icon name="plus" /></div></button></div><div v-else class="ed-empty"><Icon name="box" /><h3>{{ products.length?'No matching products':'Your catalog is ready to begin' }}</h3><p>{{ products.length?'Try another name, SKU, or category.':'Add products and stock to start taking orders.' }}</p><router-link v-if="!products.length" to="/products" class="ed-link">Open inventory<Icon name="arrow" /></router-link></div></section>
<aside ref="cartPanel" class="ed-cart"><div class="ed-cart-header"><div><h2>Current order</h2><small>{{ count }} {{ count===1?'item':'items' }} · Saved on this device</small></div><Icon name="bag" /></div><label class="ed-field"><span class="ed-eyebrow">Customer</span><select v-model="customerId" :disabled="busy"><option value="">Walk-in customer</option><option v-for="c in clients" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><div v-for="(item,i) in cart" :key="item.productId+item.variantId" class="ed-cart-item"><div style="display:flex;justify-content:space-between;gap:10px"><div><strong>{{ item.desc }}</strong><small>{{ money(item.price,currency) }} / {{ item.unit }}</small></div><button class="ed-icon-button" :aria-label="`Remove ${item.desc}`" :disabled="busy" @click="cart.splice(i,1)"><Icon name="close" /></button></div><div class="ed-cart-item-bottom"><div class="ed-quantity"><button :disabled="busy" :aria-label="`Decrease ${item.desc} quantity`" @click="updateQty(i,Number(item.qty)-1)"><Icon name="minus" /></button><input :value="item.qty" type="number" min="0.001" step="0.001" :aria-label="`${item.desc} quantity`" :disabled="busy" @change="updateQty(i,$event.target.value)"><button :disabled="busy" :aria-label="`Increase ${item.desc} quantity`" @click="updateQty(i,Number(item.qty)+1)"><Icon name="plus" /></button></div><span>{{ money(Math.round(item.price*item.qty*100)/100,currency) }}</span></div></div><div v-if="!cart.length" class="ed-empty" style="border:0"><Icon name="bag" /><h3>A fresh order.</h3><p>Choose an item to get started.</p></div><div style="padding-top:12px"><div class="ed-summary"><span>Subtotal</span><span>{{ money(totals.subtotal,currency) }}</span></div><div class="ed-summary"><span>Tax {{ totals.taxRate||0 }}%</span><span>{{ money(totals.tax,currency) }}</span></div><div class="ed-summary total"><span>Total</span><span>{{ money(totals.total,currency) }}</span></div></div><button class="ed-btn primary ed-charge" :disabled="!cart.length||busy||!ready||!!storageError" @click="openPayment"><span>Charge {{ money(totals.total,currency) }}</span><Icon name="arrow" /></button><div class="ed-cart-tools"><button class="ed-btn" :disabled="!cart.length||busy||!ready" @click="holdName='';modal='hold'">Hold order</button><button class="ed-btn" :disabled="!cart.length||busy" @click="modal='clear'">Clear</button></div><p class="ed-muted" style="font-size:10px;text-align:center;margin-top:15px">F2 to find a product · F8 to checkout</p></aside></div>
<button v-if="cart.length" class="ed-mobile-cart" @click="viewCart"><span>View order · {{ count }} items</span><strong>{{ money(totals.total,currency) }}</strong><Icon name="arrow" /></button>
<Modal v-if="modal==='variant'" :title="variantProduct.name" @close="modal=''"><p class="ed-muted" style="margin-bottom:20px">Choose an option for this product.</p><div class="ed-form-grid"><button v-for="v in variantProduct.variants" :key="v.id" class="ed-btn" style="display:block;text-align:left;white-space:normal" :disabled="variantProduct.trackStock&&available(variantProduct,v)<=0" @click="add(variantProduct,v)"><strong>{{ v.name }}</strong><small style="display:block">{{ money(v.price,currency) }}<span v-if="variantProduct.trackStock"> · {{ available(variantProduct,v) }} left</span></small></button></div></Modal>
<Modal v-if="modal==='payment'" title="Complete the order" :busy="busy" @close="modal=''"><div class="ed-payment-total"><div class="ed-eyebrow">AMOUNT TO COLLECT</div><strong>{{ money(totals.total,currency) }}</strong></div><div class="ed-payment-methods"><button v-for="m in ['Cash','QR Pay','Card']" :key="m" :class="{active:method===m}" :disabled="busy" @click="method=m;confirmed=false;error=''">{{ m }}</button></div><template v-if="method==='Cash'"><label class="ed-field"><span>Cash received ({{ currency }})</span><input v-model="received" type="number" inputmode="decimal" step="0.01" min="0" placeholder="0.00" :disabled="busy"></label><div class="ed-actions" style="margin-top:12px"><button v-for="amount in [totals.total,50,100]" :key="amount" class="ed-btn small" :disabled="busy" @click="received=amount">{{ amount===totals.total?'Exact':money(amount,currency) }}</button></div><div class="ed-summary" style="font-size:15px;margin-top:25px"><span>Change to return</span><strong>{{ money(change,currency) }}</strong></div></template><template v-else><img v-if="method==='QR Pay'&&(company.qrCode||company.qrCodeUrl)" :src="company.qrCode||company.qrCodeUrl" alt="Store payment QR code" style="width:210px;max-height:210px;object-fit:contain;margin:0 auto 20px"><div class="ed-notice"><Icon name="card" /><div><strong>Confirm on your merchant device.</strong>MyFin records the payment. Your merchant app or card terminal confirms it.</div></div><label class="ed-actions" style="font-size:13px"><input v-model="confirmed" type="checkbox" :disabled="busy">Payment confirmed on external device</label></template><div v-if="error" class="ed-alert" role="alert">{{ error }}</div><template #actions><button class="ed-btn" :disabled="busy" @click="modal=''">Back to order</button><button class="ed-btn primary" :disabled="busy" @click="complete"><Icon name="check" />{{ busy?'Saving payment…':'Complete sale' }}</button></template></Modal>
<Modal v-if="modal==='success'" :title="lastSale.syncStatus==='pending'?'Saved on this device':'A good sale.'" @close="modal=''"><div class="ed-success"><div class="ed-success-mark"><Icon name="check" /></div><h3>{{ lastSale.syncStatus==='pending'?'Payment recorded. Sync pending.':'Order complete.' }}</h3><p class="ed-muted" style="font-size:11px;word-break:break-all;margin:10px 0 25px">{{ lastSale.number }}</p><div class="ed-eyebrow">{{ lastSale.change?'CHANGE TO RETURN':'TOTAL COLLECTED' }}</div><strong>{{ money(lastSale.change||lastSale.total,currency) }}</strong></div><div v-if="lastSale.syncStatus==='pending'" class="ed-notice warning"><Icon name="cloud" /><div>Saved safely on this device. Do not take payment again. {{ lastSale.syncError || 'This receipt will sync when your connection returns.' }}</div></div><template #actions><button class="ed-btn" @click="receipt=lastSale;modal=''"><Icon name="printer" />Preview receipt</button><button class="ed-btn primary" @click="modal=''">New order<Icon name="arrow" /></button></template></Modal>
<Modal v-if="modal==='hold'" title="Keep this order for later." @close="modal=''"><label class="ed-field"><span>Order reference</span><input v-model="holdName" placeholder="Customer name or table" @keydown.enter="hold"></label><template #actions><button class="ed-btn" @click="modal=''">Cancel</button><button class="ed-btn primary" @click="hold">Hold order</button></template></Modal>
<Modal v-if="modal==='held'" title="Held orders" @close="modal=''"><div v-for="(order,i) in held" :key="order.id" class="ed-row"><div><strong>{{ order.name }}</strong><small>{{ order.items.length }} lines · {{ money(order.total,currency) }}</small></div><button class="ed-btn small" @click="restore(i)">Restore</button></div><div v-if="!held.length" class="ed-empty"><Icon name="clock" /><h3>Nothing on hold.</h3><p>Hold an order at checkout to pick it up later.</p></div><p v-else class="ed-muted" style="margin-top:18px;font-size:12px">Restoring an order parks your current cart automatically.</p></Modal>
<Modal v-if="modal==='recent'" title="Recent sales & receipts" wide @close="modal=''"><div v-for="sale in recent" :key="sale.id" class="ed-row"><div><strong style="font-size:11px">{{ sale.number }}</strong><small>{{ sale.customerName||'Walk-in customer' }} · {{ money(sale.total,currency) }}</small><span v-if="sale.syncStatus==='pending'" class="ed-pill warning">Awaiting sync</span></div><button class="ed-btn small" @click="receipt=sale;modal=''"><Icon name="printer" />Receipt</button></div><p v-if="!recent.length" class="ed-muted">Completed sales will appear here.</p></Modal>
<Modal v-if="modal==='clear'" title="Start a fresh order?" @close="modal=''"><p class="ed-muted">Clear the items from this order, or hold it if the customer will return.</p><template #actions><button class="ed-btn" @click="modal=''">Keep order</button><button class="ed-btn danger" @click="cart=[];saleId=newId();customerId='';modal=''">Clear order</button></template></Modal><Receipt v-if="receipt" :sale="receipt" @close="receipt=null" />
</div></template>
