<script setup>
import {ref,computed} from 'vue';
import {Store} from '../../store';
import {useStorage} from '../../composables/useStorage';
import {expenseRecords,money,businessDate} from '../../domain/pos';
import {expenseTemplateCsv,exportExpensesCsv,importExpensesCsv} from '../../domain/expensesCsv.js';
import Icon from '../ui/EditionIcon.vue';
import Modal from '../ui/EditionModal.vue';

const {uploadFile,removeFile}=useStorage();
const search=ref(''),form=ref(null),file=ref(null),busy=ref(false),error=ref(''),deleting=ref(null),approval=ref({managerCode:'',reason:''}),csvInput=ref(null),importBatch=ref(null);
const currency=computed(()=>Store.state.selectedCompany?.preferences?.currency||'RM');
const suppliers=computed(()=>Store.state.clients.filter(client=>client.type==='Supplier'));
const expenses=computed(()=>expenseRecords(Store.state).filter(expense=>[expense.description,expense.category,expense.payee].join(' ').toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>String(b.date).localeCompare(String(a.date))));
const total=computed(()=>expenses.value.reduce((sum,expense)=>sum+Number(expense.amount||0),0));
const supplierName=id=>suppliers.value.find(supplier=>supplier.id===id)?.name||'';
const canEditRecord=expense=>Store.can('expensesWrite')&&(expense.origin!=='transactions'||Store.permissions().owner);

function edit(expense){if(expense&&!canEditRecord(expense))return;form.value=expense?JSON.parse(JSON.stringify(expense)):{description:'',amount:'',date:businessDate(),category:'General',payee:'',supplier_id:'',receiptUrl:'',receiptPath:''};file.value=null;error.value='';}
function pick(event){const chosen=event.target.files[0];if(chosen&&chosen.size>5*1024*1024){error.value='Choose a receipt smaller than 5 MB.';event.target.value='';return;}file.value=chosen;}
function selectSupplier(){if(form.value?.supplier_id)form.value.payee=supplierName(form.value.supplier_id);}
async function save(){if(busy.value)return;error.value='';if(!form.value.description.trim()||!Number.isFinite(Number(form.value.amount))||Number(form.value.amount)<=0){error.value='Enter a description and an amount greater than zero.';return;}busy.value=true;let uploaded=null;const oldPath=form.value.receiptPath;try{if(file.value)uploaded=await uploadFile(file.value,`receipts/${Store.state.selectedCompany.id}/${crypto.randomUUID()}_${file.value.name}`);const {origin,...data}=form.value;data.amount=Math.round(Number(data.amount)*100)/100;if(uploaded){data.receiptUrl=uploaded.url;data.receiptPath=uploaded.path;}if(origin==='transactions')await Store.updateTransaction({...data,total:data.amount});else await Store.addExpense(data);if(uploaded&&oldPath&&oldPath!==uploaded.path)await removeFile(oldPath);form.value=null;Store.notify('Expense saved.');}catch(caught){error.value=caught.message;}finally{busy.value=false;}}
async function remove(){busy.value=true;try{if(deleting.value.origin==='transactions')throw new Error('Historical expenses require a correction workflow.');await Store.deleteExpense(deleting.value.id,approval.value);deleting.value=null;approval.value={managerCode:'',reason:''};Store.notify('Expense voided. Its audit history was retained.');}catch(caught){Store.notify(caught.message,'error');}finally{busy.value=false;}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCsv(){download(exportExpensesCsv(expenses.value,suppliers.value),'myfin-expenses.csv');}
function templateCsv(){download(expenseTemplateCsv(businessDate()),'myfin-expense-upload-template.csv');}
async function readCsv(event){error.value='';const chosen=event.target.files?.[0];event.target.value='';if(!chosen)return;try{if(chosen.size>1024*1024)throw new Error('Choose a CSV file smaller than 1 MB.');const rows=importExpensesCsv(await chosen.text(),suppliers.value);importBatch.value={name:chosen.name,batchId:crypto.randomUUID(),rows};}catch(caught){Store.notify(caught.message,'error');}}
async function importCsv(){if(!importBatch.value||busy.value)return;busy.value=true;error.value='';try{const result=await Store.importExpenses({batchId:importBatch.value.batchId,rows:importBatch.value.rows});importBatch.value=null;Store.notify(result.alreadyImported?`${result.count} expenses were already imported. No duplicates were created.`:`${result.count} expenses imported.`);}catch(caught){error.value=caught.message;}finally{busy.value=false;}}
</script>

<template><div v-if="Store.can('expensesRead') && Store.state.online" class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">WORKSPACE / EXPENSES</div><h1>Keep the outgoings in view.</h1><p>Operators can record expenses; managers control later changes and spreadsheet imports.</p></div><div class="ed-actions"><template v-if="Store.can('expensesWrite')"><button class="ed-btn" @click="templateCsv"><Icon name="download"/>CSV template</button><button class="ed-btn" @click="csvInput.click()"><Icon name="arrow-up"/>Upload CSV</button><input ref="csvInput" type="file" accept=".csv,text/csv" hidden @change="readCsv"></template><button v-if="Store.permissions().owner||Store.permissions().manager" class="ed-btn" @click="exportCsv"><Icon name="download"/>Export</button><button class="ed-btn primary" @click="edit()"><Icon name="plus"/>Record expense</button></div></header><div class="ed-filters"><div class="ed-search"><Icon name="search"/><input v-model="search" class="ed-input" aria-label="Search expenses" placeholder="Search description, category or payee"></div><div style="text-align:right"><div class="ed-eyebrow">TOTAL SHOWN</div><strong style="font-size:23px;font-weight:500">{{ money(total,currency) }}</strong></div></div><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Expense</th><th>Category</th><th>Paid to</th><th>Date</th><th class="num">Amount</th><th>Receipt</th><th>Actions</th></tr></thead><tbody><tr v-for="expense in expenses" :key="expense.origin+expense.id"><td><button v-if="canEditRecord(expense)" class="ed-link" @click="edit(expense)">{{ expense.description }}</button><strong v-else>{{ expense.description }}</strong><small v-if="expense.origin==='transactions'">Legacy {{ expense.type.toLowerCase() }}</small></td><td><span class="ed-pill">{{ expense.category||'General' }}</span></td><td>{{ supplierName(expense.supplier_id)||expense.payee||'—' }}</td><td>{{ businessDate(expense.date) }}</td><td class="num">{{ money(expense.amount,currency) }}</td><td><a v-if="expense.receiptUrl" class="ed-link" :href="expense.receiptUrl" target="_blank" rel="noopener">View ↗</a><span v-else class="ed-muted">—</span></td><td><button v-if="canEditRecord(expense)" class="ed-icon-button" :aria-label="`Edit ${expense.description}`" @click="edit(expense)"><Icon name="edit"/></button><button v-if="expense.origin!=='transactions'" class="ed-icon-button" :aria-label="`Void ${expense.description}`" @click="deleting=expense;approval={managerCode:'',reason:''}"><Icon name="close"/></button></td></tr></tbody></table></div><div v-if="!expenses.length" class="ed-empty"><Icon name="wallet"/><h3>No expenses here yet.</h3><p>Add an expense or try a different search.</p></div>
  <Modal v-if="form" :title="form.id?'Edit expense':'Record an expense'" :busy="busy" @close="form=null"><form id="expense-form" class="ed-form-grid" @submit.prevent="save"><label class="ed-field wide"><span>Description</span><input v-model="form.description" required></label><label class="ed-field"><span>Amount ({{ currency }})</span><input v-model="form.amount" type="number" step="0.01" min="0.01" required></label><label class="ed-field"><span>Date</span><input v-model="form.date" type="date" required></label><label class="ed-field"><span>Category</span><select v-model="form.category"><option v-for="category in ['General','Inventory','Operations','Utilities','Rent','Salaries','Equipment','Marketing','Software/SaaS','Travel']" :key="category">{{ category }}</option></select></label><label v-if="Store.can('suppliersRead')" class="ed-field"><span>Supplier · optional</span><select v-model="form.supplier_id" @change="selectSupplier"><option value="">None</option><option v-for="supplier in suppliers" :key="supplier.id" :value="supplier.id">{{ supplier.name }}</option></select></label><label class="ed-field"><span>Paid to</span><input v-model="form.payee"></label><label class="ed-field wide"><span>Receipt · optional, up to 5 MB</span><input type="file" accept="image/*,application/pdf" @change="pick"><small v-if="form.receiptUrl&&!file" class="ed-muted">A receipt is attached. Upload a file to replace it.</small></label></form><p v-if="error" class="ed-alert" role="alert">{{ error }}</p><template #actions><button class="ed-btn" :disabled="busy" @click="form=null">Cancel</button><button class="ed-btn primary" :disabled="busy" type="submit" form="expense-form">{{ busy?'Saving…':'Save expense' }}</button></template></Modal>
  <Modal v-if="importBatch" title="Review expense import" :busy="busy" wide @close="importBatch=null"><p><strong>{{ importBatch.rows.length }}</strong> expenses from {{ importBatch.name }} are ready to import.</p><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Supplier / payee</th><th class="num">Amount</th></tr></thead><tbody><tr v-for="(row,index) in importBatch.rows.slice(0,10)" :key="index"><td>{{ row.date }}</td><td>{{ row.description }}</td><td>{{ row.category }}</td><td>{{ supplierName(row.supplier_id)||row.payee||'—' }}</td><td class="num">{{ money(row.amount,currency) }}</td></tr></tbody></table></div><p v-if="importBatch.rows.length>10" class="ed-muted">Showing the first 10 rows. All {{ importBatch.rows.length }} validated rows will be imported together.</p><p v-if="error" class="ed-alert" role="alert">{{ error }}</p><template #actions><button class="ed-btn" :disabled="busy" @click="importBatch=null">Cancel</button><button class="ed-btn primary" :disabled="busy" @click="importCsv">{{ busy?'Importing…':`Import ${importBatch.rows.length} expenses` }}</button></template></Modal>
  <Modal v-if="deleting" title="Void this expense?" :busy="busy" @close="deleting=null"><p>{{ deleting.description }} · {{ money(deleting.amount,currency) }}</p><label class="ed-field"><span>Reason</span><input v-model="approval.reason" minlength="3" placeholder="Why this entry is being voided"></label><label v-if="Store.permissions().operator" class="ed-field"><span>Manager approval code</span><input v-model="approval.managerCode" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" placeholder="000000"></label><p class="ed-muted">The entry remains in the audit history.</p><template #actions><button class="ed-btn" :disabled="busy" @click="deleting=null">Keep expense</button><button class="ed-btn danger" :disabled="busy||approval.reason.trim().length<3||(Store.permissions().operator&&!/^\d{6}$/.test(approval.managerCode))" @click="remove">Void expense</button></template></Modal>
</div><div v-else class="ed-notice">Connect with an authorized company account to view this page.</div></template>
