<script setup>
import { computed, ref } from 'vue';
import { Store } from '../../store';
import { isPaid, money, businessDate } from '../../domain/pos';
import Icon from '../ui/EditionIcon.vue';
const period=ref('Week');
const currency=computed(()=>Store.state.selectedCompany?.preferences?.currency||'RM');
const paid=computed(()=>Store.state.transactions.filter(isPaid));
const today=businessDate();
const daySales=computed(()=>paid.value.filter(t=>businessDate(t.date)===today));
const total=computed(()=>daySales.value.reduce((s,t)=>s+Number(t.total||0),0));
const outstanding=computed(()=>Store.state.transactions.filter(t=>t.type==='Invoice'&&!isPaid(t)&&t.status!=='Voided'));
const unpaid=computed(()=>outstanding.value.reduce((s,t)=>s+Number(t.total||0),0));
const lowStock=computed(()=>Store.state.products.filter(p=>p.trackStock&&(p.variants.length?p.variants.some(v=>v.stock<5):p.stock<5)));
const recent=computed(()=>[...Store.state.transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6));
const customer=t=>t.customerName||Store.state.clients.find(c=>c.id===t.client_id)?.name||'Walk-in customer';
const bestsellers=computed(()=>{const tally={};paid.value.forEach(t=>(t.items||[]).forEach(i=>{const key=i.productId||i.desc;tally[key]??={name:i.desc||i.name,qty:0,total:0};tally[key].qty+=Number(i.qty||0);tally[key].total+=Number(i.price||0)*Number(i.qty||0);}));return Object.values(tally).sort((a,b)=>b.qty-a.qty).slice(0,4);});
const chart=computed(()=>{const count=period.value==='Week'?7:30;return Array.from({length:count},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(count-1-i));const date=businessDate(d);return {date,label:d.toLocaleDateString('en-MY',{weekday:'short',day:'numeric'}),total:paid.value.filter(t=>businessDate(t.date)===date).reduce((s,t)=>s+Number(t.total||0),0)};});});
const chartTotal=computed(()=>chart.value.reduce((s,d)=>s+d.total,0));
const points=computed(()=>{const max=Math.max(...chart.value.map(d=>d.total),1);return chart.value.map((d,i)=>`${i*600/(chart.value.length-1)},${170-d.total/max*150}`).join(' ');});
const shortage=computed(()=>Store.state.transactions.filter(t=>t.stockShortage).length);
</script>
<template><div class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">STORE OVERVIEW / {{ Store.state.selectedCompany?.name }}</div><h1>Your shop, at a glance.</h1><p>{{ new Date().toLocaleDateString('en-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'}) }}. Good {{ new Date().getHours()<12?'morning':'day' }}, {{ Store.state.currentUser?.username }}.</p></div><div class="ed-actions"><router-link to="/pos" class="ed-btn primary"><Icon name="bag" />Open checkout</router-link></div></header>
<div class="ed-metrics"><div class="ed-metric"><label>Sales today</label><strong><span class="ed-currency">{{ currency }}</span>{{ total.toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2}) }}</strong><small>Paid & cleared invoices</small></div><div class="ed-metric"><label>Transactions today</label><strong>{{ daySales.length }}</strong><small>Completed sales</small></div><div class="ed-metric"><label>Average sale</label><strong><span class="ed-currency">{{ currency }}</span>{{ (total/(daySales.length||1)).toFixed(2) }}</strong><small>Today's completed sales</small></div><div class="ed-metric"><label>Outstanding invoices</label><strong><span class="ed-currency">{{ currency }}</span>{{ unpaid.toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2}) }}</strong><small>{{ outstanding.length }} awaiting payment</small></div></div>
<div class="ed-two-col"><section><div class="ed-section-head"><div><h2>Sales performance</h2><small>{{ money(chartTotal,currency) }} this {{ period.toLowerCase() }}</small></div><div class="ed-segmented"><button v-for="p in ['Week','Month']" :key="p" :class="{active:period===p}" @click="period=p">{{ p }}</button></div></div><svg viewBox="0 0 600 195" role="img" :aria-label="`Paid sales over the last ${chart.length} days: ${money(chartTotal,currency)}`" style="width:100%;height:220px;overflow:visible"><line v-for="y in [20,70,120,170]" :key="y" x1="0" x2="600" :y1="y" :y2="y" stroke="var(--ed-line)"/><polygon :points="`0,170 ${points} 600,170`" fill="var(--ed-accent)" opacity=".06"/><polyline :points="points" fill="none" stroke="var(--ed-accent)" stroke-width="2.5" vector-effect="non-scaling-stroke"/></svg><div style="display:flex;justify-content:space-between;font-size:11px" class="ed-muted"><span>{{ chart[0].label }}</span><span>{{ chart[Math.floor(chart.length/2)].label }}</span><span>{{ chart.at(-1).label }}</span></div><div class="ed-row"><span>● Paid sales</span><router-link to="/analytics" class="ed-link">Explore analytics<Icon name="arrow" /></router-link></div></section><aside class="ed-side-section"><div class="ed-section-head"><h2>Worth a look</h2><span class="ed-pill">{{ lowStock.length+outstanding.length+shortage }} updates</span></div><div class="ed-row"><div><strong>{{ lowStock.length }} products running low</strong><small>Check stock before the next sale.</small><router-link to="/products" class="ed-link" style="margin-top:8px">Review inventory<Icon name="arrow" /></router-link></div></div><div class="ed-row"><div><strong>{{ money(unpaid,currency) }} awaiting payment</strong><small>{{ outstanding.length }} open invoices</small><router-link to="/sales" class="ed-link" style="margin-top:8px">Open sales<Icon name="arrow" /></router-link></div></div><div v-if="shortage" class="ed-notice warning"><Icon name="alert" /><div>{{ shortage }} offline sales recorded a stock shortage. Review inventory with your manager.</div></div><div style="padding:20px;background:var(--ed-citrus);margin-top:23px"><div class="ed-eyebrow">YOUR NEXT GOOD SALE</div><router-link to="/pos" class="ed-link" style="font-size:14px!important;margin-top:9px">Ready for the next customer?<Icon name="arrow" /></router-link></div></aside></div>
<div class="ed-two-col ed-section"><section><div class="ed-section-head"><h2>Recent transactions</h2><router-link to="/sales" class="ed-link">View all<Icon name="arrow" /></router-link></div><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Receipt / document</th><th>Customer</th><th>Status</th><th class="num">Amount</th></tr></thead><tbody><tr v-for="t in recent" :key="t.id"><td><router-link to="/sales" class="ed-link">{{ t.number || t.type }}</router-link><small>{{ businessDate(t.date) }}</small></td><td>{{ customer(t) }}</td><td><span class="ed-pill" :class="{warning:!isPaid(t)}">{{ isPaid(t)?'Paid':t.status||'Pending' }}</span></td><td class="num">{{ money(t.total??t.amount,currency) }}</td></tr><tr v-if="!recent.length"><td colspan="4" class="ed-muted">Your transactions will appear here after your first sale.</td></tr></tbody></table></div></section><aside class="ed-side-section"><div class="ed-section-head"><h2>Bestsellers</h2><span class="ed-muted" style="font-size:11px">All time</span></div><div v-for="(p,i) in bestsellers" :key="p.name" class="ed-row"><span class="ed-muted">0{{ i+1 }}</span><div style="flex:1"><strong>{{ p.name }}</strong><small>{{ p.qty }} sold</small></div><span>{{ money(p.total,currency) }}</span></div><p v-if="!bestsellers.length" class="ed-muted">Your most popular items will appear after completed sales.</p></aside></div>
</div></template>
