<script setup>
import {computed,ref,onMounted,watch} from 'vue';
import {Store} from '../../store';
import {needsReceiptReview} from '../../domain/offlinePolicy';
import {money} from '../../domain/pos';
import Modal from '../ui/EditionModal.vue';
const busy=ref(false),error=ref(''),selected=ref(null),reason=ref('');
const rows=computed(()=>Store.state.receiptReviews||[]);
const ownNeedsReview=computed(()=>Store.state.pendingSales.filter(s=>needsReceiptReview(s.syncError)&&!rows.value.some(r=>r.id===s.id)));
const status=computed(()=>Store.state.online?'The original cashier must reconnect and retry sync after approval. Keep this browser’s data until the queue is empty.':'Reconnect to request or approve a review. Paid receipts remain saved on this device.');
const isPosted=row=>['posted','approved'].includes(row.status);
const canApprove=computed(()=>Store.can('documentsIssue'));
const currency=sale=>sale.storeSnapshot?.currency||Store.state.selectedCompany?.preferences?.currency||'RM';
function reasonText(code){return ({receipt_review_required_pricing_policy:'Catalog price, tax or discount policy changed',receipt_review_required_merchant_changed:'Original merchant details differ from current settings',receipt_review_required_product_changed:'The original product option changed; reconcile the catalog before approval',stock_unavailable:'Stock needs review',price_changed:'Catalog price changed',tax_changed:'Tax policy changed',merchant_changed:'Receipt details changed',receipt_review_required:'Recorded payment differs from current checkout policy'})[code]||'Recorded payment needs review against the current checkout policy';}
async function refresh(){error.value='';try{await Store.refreshActor();await Store.refreshReceiptReviews();}catch(e){error.value=e.message;}}
async function request(sale){busy.value=true;error.value='';try{await Store.requestReceiptReview(sale);Store.notify('Payment review requested. Keep the original receipt queued until sync confirms it.');}catch(e){error.value='Review could not be confirmed. The original payment is still queued; retry safely when connected.';}finally{busy.value=false;}}
function choose(row){selected.value=row;reason.value='';error.value='';}
async function approve(){if(busy.value)return;error.value='';if(reason.value.trim().length<3){error.value='Enter an approval reason of at least 3 characters.';return;}busy.value=true;try{await Store.approveReceiptReview(selected.value.id,reason.value);selected.value=null;Store.notify('Original payment approved. The cashier can now retry sync.');}catch(e){error.value=e.message;}finally{busy.value=false;}}
onMounted(refresh);
watch(()=>Store.state.selectedCompany?.id,()=>{selected.value=null;refresh();});
</script>
<template><div v-if="Store.can('checkout')" class="ed-page"><header class="ed-page-head"><div><div class="ed-eyebrow">WORKSPACE / PAYMENT REVIEWS</div><h1>Resolve recorded payments.</h1><p>{{ canApprove?'Review the original amount and cashier before approval.':'Track your paid receipts that need manager approval.' }}</p></div><button class="ed-btn" :disabled="busy||!Store.state.online" @click="refresh">Refresh reviews</button></header>
<div class="ed-notice warning">{{ status }}</div><p v-if="error" class="ed-alert" role="alert">{{ error }}</p>
<section v-if="ownNeedsReview.length"><h2>Ready to request review</h2><div v-for="sale in ownNeedsReview" :key="sale.id" class="ed-row"><div><strong>{{ sale.number }}</strong><small>{{ money(sale.total,currency(sale)) }} · Original cashier: {{ sale.cashierId }}</small></div><button class="ed-btn" :disabled="busy||!Store.state.online" @click="request(sale)">Request review</button></div></section>
<div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>Original receipt</th><th>Cashier</th><th>Recorded amount</th><th>Review</th><th>Action</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><strong>{{ row.sale.number||row.id }}</strong><small>{{ row.sale.customerName||'Walk-in customer' }}</small><small>{{ row.sale.date }}</small></td><td>{{ row.sale.cashierId }}</td><td>{{ money(row.sale.total,currency(row.sale)) }}</td><td><span class="ed-pill">{{ isPosted(row)?'Approved and posted':'Awaiting approval' }}</span><small>{{ reasonText(row.reasonCode) }}</small></td><td><button v-if="!isPosted(row)&&canApprove" class="ed-btn small" :disabled="busy||!Store.state.online" @click="choose(row)">Review payment</button><button v-else-if="isPosted(row)&&row.sale.cashierId===Store.state.currentUser?.uid" class="ed-btn small" :disabled="Store.state.syncing||!Store.state.online" @click="Store.syncSales()">Retry sync</button><span v-else class="ed-muted">{{ isPosted(row)?'Cashier can retry sync':'A manager must approve' }}</span></td></tr></tbody></table></div>
<div v-if="!rows.length&&!ownNeedsReview.length" class="ed-empty"><h3>No payments awaiting review.</h3><p>Payments that cannot sync under current checkout policy will appear here.</p></div>
<Modal v-if="selected" title="Review original payment" :busy="busy" @close="selected=null"><div class="ed-notice warning">Approve only after checking the original receipt and payment. This records the saved amount once and deducts stock once; it does not charge the customer.</div><dl><dt>Receipt</dt><dd>{{ selected.sale.number||selected.id }}</dd><dt>Original cashier</dt><dd>{{ selected.sale.cashierId }}</dd><dt>Recorded amount</dt><dd>{{ money(selected.sale.total,currency(selected.sale)) }}</dd><dt>Payment method</dt><dd>{{ selected.sale.paymentMethod }}</dd></dl><div v-for="(item,i) in selected.sale.items" :key="i" class="ed-row"><span>{{ item.desc }} × {{ item.qty }}</span><strong>{{ money(item.price,currency(selected.sale)) }} each</strong></div><label class="ed-field"><span>Approval reason</span><textarea v-model="reason" rows="3" maxlength="500" :disabled="busy" placeholder="Explain why the original recorded amount is valid."></textarea></label><p v-if="error" class="ed-alert" role="alert">{{ error }}</p><template #actions><button class="ed-btn" :disabled="busy" @click="selected=null">Cancel</button><button class="ed-btn primary" :disabled="busy||reason.trim().length<3" @click="approve">{{ busy?'Confirming…':'Approve original payment' }}</button></template></Modal>
</div></template>
