import { cents } from "../../src/domain/pos.js";
import { permissionsFor } from "../../src/domain/permissions.js";
import { fail } from "./validation.js";
export const owner=who=>["super_admin","super","workspace_owner"].includes(who.role);
export const manager=who=>["manager","company_admin"].includes(who.role);
export const operator=who=>["operator","company_user"].includes(who.role);
export function requireCapability(who,capability){if(!permissionsFor(who)[capability])fail(403,"access_denied");}
const confidential=/^(cost|unitCost|purchasePrice|costPrice|margin|profit|grossProfit|netProfit|expense|expenses|valuation|inventoryValue|costTotal)$/i;
export function containsConfidential(value){if(!value||typeof value!=="object")return false;return Object.entries(value).some(([key,v])=>confidential.test(key)||containsConfidential(v));}
// Legacy JSON must not smuggle private objects through otherwise allowed scalar fields.
const pick=(value,keys)=>Object.fromEntries(keys.filter(key=>value?.[key]!==undefined&&(value[key]===null||["string","number","boolean"].includes(typeof value[key]))).map(key=>[key,value[key]]));
const itemKeys=["productId","variantId","variant","sku","desc","price","unit","qty"];
export function publicCompany(data,who){if(owner(who))return data;return {...pick(data,["id","name","registration","address","phone","email","logo","qrCode","qrCodeUrl"]),preferences:pick(data.preferences||{},["theme","currency","tax","taxRate","staffDiscountLimit","receiptFooter","paperWidth","density","reduceMotion","baseTheme","primaryColor","fontFamily","showLogo","defaultNotes","labels"]),...(data.receiptTemplate?{receiptTemplate:{id:data.receiptTemplate.id,version:data.receiptTemplate.version,settings:publicTemplate(data.receiptTemplate.settings)}}:{})};}
export function publicStockMovement(data,who){if(owner(who))return data;return {...pick(data,["id","company_id","saleId","date","cashierId","action","shortage"]),movements:(data.movements||[]).map(item=>pick(item,["productId","variantId","quantity","stockAfter"]))};}
export function publicProduct(data,who){if(owner(who))return data;return {...pick(data,["id","company_id","version","name","sku","code","barcode","category","unit","price","stock","trackStock","hasVariants","description","imageUrl","imagePath"]),variants:(data.variants||[]).map(v=>pick(v,["id","name","sku","barcode","price","stock"]))};}
export function publicClient(data,who){return owner(who)?data:pick(data,["id","company_id","name","email","phone","type","address","registration","notes"]);}
const snapshotKeys=["id","number","type","status","documentState","date","dueDate","validUntil","notes","paymentInstructions","terms","footer","signatureLabel","correctionOf","templateId","templateVersion","subtotal","discountAmount","tax","taxRate","discount","total"];
const companyKeys=["name","registration","address","phone","email","logo","qrCode","currency"];
const customerKeys=["name","registration","address","phone","email"];
const settingsKeys=["layout","primaryColor","fontFamily","showLogo","showPaymentQr","showSignature","signatureLabel","paymentInstructions","bankName","accountName","accountNumber","terms","footer","paperWidth"];
export function publicTemplate(settings={}){return {...pick(settings,settingsKeys),labels:pick(settings.labels||{},["title","billTo","total"])};}
export function publicSnapshot(data={}){const company=pick(data.companySnapshot||data.company||{},companyKeys),customer=pick(data.clientSnapshot||data.customer||{},customerKeys),template=publicTemplate(data.templateSnapshot||data.template||{});return {...pick(data,snapshotKeys),items:(data.items||[]).map(item=>pick(item,itemKeys)),companySnapshot:company,clientSnapshot:customer,templateSnapshot:template,company,customer,template};}
export function publicTransaction(data,who){if(owner(who))return data;return {...pick(data,[...snapshotKeys,"id","company_id","source","client_id","project","quoteId","convertedTo","schemaVersion","cashierId","cashierName","businessDate","paymentMethod","received","change","customerName","customerEmail","offline","stockShortage","createdBy","assignedTo","version","issuedAt","templateId","paymentStatus","paidAmount","outstandingAmount","overrideReason","receiptTemplateId","receiptTemplateVersion"]),items:(data.items||[]).map(item=>pick(item,itemKeys)),...(data.storeSnapshot?{storeSnapshot:pick(data.storeSnapshot,["name","address","phone","registration","currency","footer","paperWidth"])}:{}),...(data.companySnapshot?{companySnapshot:pick(data.companySnapshot,companyKeys)}:{}),...(data.templateSnapshot?{templateSnapshot:publicTemplate(data.templateSnapshot)}:{}),...(data.issuedSnapshot?{issuedSnapshot:publicSnapshot(data.issuedSnapshot)}:{}),...(data.payments?{payments:data.payments.map(payment=>pick(payment,["id","amount","method","reference","date"]))}:{})};}
export function recordVisible(row,who){
 if(owner(who))return true;
 if(row.source==="pos")return manager(who)||row.actor_id===who.id;
 if(!["Invoice","Quote"].includes(row.data?.type)||row.document_state==="legacy")return false;
 return manager(who)||(row.document_state==="draft"&&(row.actor_id===who.id||row.assigned_to===who.id));
}
export function recordOutput(row,who){const paid=Number(row.paid_amount||0),total=Number(row.total||0);return publicTransaction({...row.data,id:row.id,company_id:row.company_id,createdBy:row.actor_id,assignedTo:row.assigned_to||"",documentState:row.source==="pos"?"issued":row.document_state,version:row.document_version,issuedAt:row.issued_at,issuedSnapshot:row.issued_snapshot,payments:row.payments||[],quoteId:row.quote_id||row.data.quoteId,convertedTo:row.converted_to||row.data.convertedTo,correctionOf:row.correction_of||row.data.correctionOf,...(row.document_state!=="legacy"&&row.source!=="pos"?{status:row.document_state==="draft"?"Draft":row.document_state==="voided"?"Voided":row.document_state==="corrected"?"Corrected":row.data.type==="Quote"?(row.converted_to?"Converted":"Issued"):(paid>=total?"Paid":paid>0?"Partially paid":"Pending"),paidAmount:paid,outstandingAmount:Math.max(0,cents(total)-cents(paid))/100}:{})},who);}
