<script setup>
import { computed } from 'vue';
import { money } from '../../../domain/pos';
const props = defineProps({ document: { type: Object, required: true }, compact: Boolean });
const doc = computed(() => props.document);
const currency = computed(() => doc.value.currency || 'RM');
const total = value => money(value || 0, currency.value);
const date = value => value ? String(value).slice(0,10) : '—';
</script>
<template>
  <article class="mf-document" :class="['mf-document--'+doc.format,'mf-document--'+doc.settings.layout,{compact}]" :style="{'--document-accent':doc.settings.primaryColor,fontFamily:doc.settings.fontFamily==='serif'?'Georgia, serif':'Arial, sans-serif',width:doc.format==='receipt'?(doc.settings.paperWidth==='58'?'58mm':'80mm'):'100%',maxWidth:doc.format==='receipt'?'100%':undefined}" aria-label="Document preview">
    <div v-if="doc.pending" class="mf-document-notice">Payment recorded on this device · Awaiting server sync</div>
    <div v-if="doc.invalid" class="mf-document-notice" role="status">{{ doc.previewError }}</div>
    <div v-if="doc.isDraft" class="mf-document-notice">DRAFT · Not issued</div>
    <header class="mf-document-header">
      <div class="mf-document-business">
        <img v-if="doc.settings.showLogo && doc.company.logo" :src="doc.company.logo" class="mf-document-logo" alt="Company logo">
        <h2>{{ doc.company.name }}</h2>
        <p v-if="doc.company.registration">Registration: {{ doc.company.registration }}</p>
        <p v-if="doc.company.address" class="mf-document-pre">{{ doc.company.address }}</p>
        <p v-if="doc.company.phone">{{ doc.company.phone }}</p>
        <p v-if="doc.company.email">{{ doc.company.email }}</p>
      </div>
      <div class="mf-document-identity"><h1>{{ doc.settings.labels.title }}</h1><strong>{{ doc.number || 'Assigned when issued' }}</strong><span v-if="doc.isPaid" class="mf-document-paid">PAID</span><small v-else-if="doc.status && !doc.isDraft">{{ doc.status }}</small></div>
    </header>
    <section class="mf-document-parties">
      <div><h3>{{ doc.settings.labels.billTo }}</h3><strong>{{ doc.customer.name || 'Walk-in customer' }}</strong><p v-if="doc.customer.registration">{{ doc.customer.registration }}</p><p v-if="doc.customer.address" class="mf-document-pre">{{ doc.customer.address }}</p><p v-if="doc.customer.email">{{ doc.customer.email }}</p><p v-if="doc.customer.phone">{{ doc.customer.phone }}</p></div>
      <dl><div><dt>{{ doc.format === 'receipt' ? 'Date & time' : 'Issue date' }}</dt><dd>{{ doc.displayDate || date(doc.date) }}</dd></div><div v-if="doc.dueDate"><dt>Payment due</dt><dd>{{ date(doc.dueDate) }}</dd></div><div v-if="doc.validUntil"><dt>Quote valid until</dt><dd>{{ date(doc.validUntil) }}</dd></div><div v-if="doc.project"><dt>Project</dt><dd>{{ doc.project }}</dd></div><div v-if="doc.cashierName"><dt>Cashier</dt><dd>{{ doc.cashierName }}</dd></div></dl>
    </section>
    <table v-if="doc.format==='receipt'" class="mf-document-items mf-document-receipt-items"><thead><tr><th scope="col">Description</th><th scope="col">Amount</th></tr></thead><tbody><tr v-for="(item,index) in doc.items" :key="index"><td><strong>{{ item.desc }}</strong><small>{{ item.qty }} {{ item.unit }} × {{ total(item.price) }}</small></td><td>{{ total(item.amount) }}</td></tr></tbody></table>
    <table v-else class="mf-document-items"><thead><tr><th scope="col">Description</th><th scope="col">Qty</th><th scope="col">Unit price</th><th scope="col">Amount</th></tr></thead><tbody><tr v-for="(item,index) in doc.items" :key="index"><td><strong>{{ item.desc }}</strong><small v-if="item.unit">{{ item.unit }}</small></td><td>{{ item.qty }}</td><td>{{ total(item.price) }}</td><td>{{ total(item.amount) }}</td></tr><tr v-if="!doc.items.length"><td colspan="4">Add a line item to preview this document.</td></tr></tbody></table>
    <div v-if="!doc.invalid" class="mf-document-totals"><dl><div><dt>Subtotal</dt><dd>{{ total(doc.subtotal) }}</dd></div><div v-if="doc.discountAmount"><dt>Discount ({{ doc.discount }}%)</dt><dd>− {{ total(doc.discountAmount) }}</dd></div><div v-if="doc.tax || doc.taxRate"><dt>Tax ({{ doc.taxRate }}%)</dt><dd>{{ total(doc.tax) }}</dd></div><div class="mf-document-total"><dt>{{ doc.settings.labels.total }}</dt><dd>{{ total(doc.total) }}</dd></div><div v-if="doc.paymentMethod"><dt>Payment</dt><dd>{{ doc.paymentMethod }}</dd></div><div v-if="doc.received != null"><dt>Received</dt><dd>{{ total(doc.received) }}</dd></div><div v-if="doc.change != null"><dt>Change</dt><dd>{{ total(doc.change) }}</dd></div><div v-if="doc.format !== 'receipt' && doc.amountPaid"><dt>Payments recorded</dt><dd>{{ total(doc.amountPaid) }}</dd></div><div v-if="doc.format !== 'receipt' && doc.kind === 'Invoice' && !doc.isDraft && doc.balance != null"><dt>Balance due</dt><dd>{{ total(doc.balance) }}</dd></div></dl></div>
    <section v-if="doc.paymentInstructions || (doc.settings.showPaymentQr && doc.company.qrCode)" class="mf-document-section"><h3>Payment instructions</h3><p v-if="doc.paymentInstructions" class="mf-document-pre">{{ doc.paymentInstructions }}</p><img v-if="doc.settings.showPaymentQr && doc.company.qrCode" :src="doc.company.qrCode" class="mf-document-qr" alt="Payment QR code"></section>
    <section v-if="doc.notes" class="mf-document-section"><h3>Notes</h3><p class="mf-document-pre">{{ doc.notes }}</p></section>
    <section v-if="doc.terms" class="mf-document-section"><h3>{{ doc.kind === 'Quote' ? 'Terms & acceptance' : 'Terms' }}</h3><p class="mf-document-pre">{{ doc.terms }}</p></section>
    <section v-if="doc.settings.showSignature" class="mf-document-signature"><div></div><p>{{ doc.settings.signatureLabel || 'Authorized signature' }}</p></section>
    <footer v-if="doc.footer">{{ doc.footer }}</footer>
  </article>
</template>
<style>
.mf-document{background:#fff;color:#202e2b;padding:clamp(18px,5%,44px);font-size:12px;line-height:1.5;max-width:794px;margin:0 auto;width:100%;box-sizing:border-box;overflow-wrap:anywhere}
.mf-document *{box-sizing:border-box}.mf-document p{margin:3px 0}.mf-document h1{font-family:inherit;font-size:clamp(24px,4vw,34px);font-weight:700;letter-spacing:.025em;color:var(--document-accent);margin:0 0 8px}.mf-document h2{font-size:19px;font-weight:700;line-height:1.3;margin:6px 0}.mf-document h3{font-size:10px;letter-spacing:.08em;text-transform:uppercase;font-weight:700;color:var(--document-accent);margin:0 0 8px}
.mf-document-header{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:22px;border-bottom:2px solid var(--document-accent);padding-bottom:22px;margin-bottom:22px}.mf-document-identity{text-align:right;min-width:0}.mf-document-identity>strong,.mf-document-identity>small{display:block}.mf-document-logo{max-width:140px;max-height:66px;object-fit:contain;margin-bottom:8px}.mf-document-pre{white-space:pre-line}.mf-document-parties{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:26px}.mf-document dl{margin:0}.mf-document dl>div{display:flex;justify-content:space-between;gap:16px;padding:3px 0}.mf-document dt{color:#60716b}.mf-document dd{margin:0;text-align:right}.mf-document-parties dl{font-size:11px}.mf-document-paid{display:inline-block;color:#176044;border:2px solid #176044;padding:3px 11px;margin-top:9px;font-weight:700;letter-spacing:.1em}
.mf-document-items{border-collapse:collapse;width:100%;font-size:12px;table-layout:fixed}.mf-document-items th{padding:9px 6px;text-align:right;border-bottom:1px solid var(--document-accent);color:var(--document-accent);font-size:10px;font-weight:700}.mf-document-items td{padding:12px 6px;text-align:right;vertical-align:top;border-bottom:1px solid #e0e6e2;font-variant-numeric:tabular-nums;overflow-wrap:normal}.mf-document-items :is(th,td):first-child{width:48%;text-align:left;overflow-wrap:anywhere;padding-left:0;white-space:pre-line}.mf-document-items :is(th,td):nth-child(2){width:10%}.mf-document-items :is(th,td):last-child{padding-right:0}.mf-document-items td strong{font-weight:500}.mf-document-items td small{display:block;color:#66786f;white-space:normal;margin-top:3px}.mf-document-totals{display:flex;justify-content:flex-end;margin:20px 0}.mf-document-totals dl{min-width:245px;max-width:100%}.mf-document-total{border-top:1px solid #9baea5;font-size:17px;font-weight:700;margin-top:8px;padding-top:9px!important}.mf-document-total dt{color:inherit}.mf-document-section{border-top:1px solid #e0e6e2;padding-top:16px;margin-top:20px}.mf-document-qr{display:block;width:110px;height:110px;object-fit:contain;margin-top:12px}.mf-document-signature{margin-top:45px;max-width:220px}.mf-document-signature>div{border-top:1px solid #a6b5ae}.mf-document-signature p{font-size:10px;color:#66786f;margin-top:7px}.mf-document footer{border-top:1px solid #d1ddd6;padding-top:15px;margin-top:28px;text-align:center;font-size:10px;color:#5e7167;white-space:pre-line}.mf-document-notice{border:1px dashed #b98945;color:#835f2a;padding:9px 12px;margin-bottom:20px;font-size:11px;letter-spacing:.02em}
.mf-document--corporate .mf-document-header{background:#f3f5f2;padding:18px;border:1px solid #d6dfd9}.mf-document--corporate .mf-document-items th,.mf-document--modern .mf-document-items th{background:var(--document-accent);color:white;border:0;padding:10px 8px}.mf-document--corporate .mf-document-items td,.mf-document--modern .mf-document-items td{padding-inline:8px}.mf-document--modern .mf-document-header{border-bottom-width:4px}.mf-document--modern .mf-document-parties{border-left:3px solid var(--document-accent);padding-left:15px}.mf-document--modern .mf-document-totals dl{padding:12px;background:#f3f5f2}
.mf-document--receipt{font-family:Consolas,monospace!important;max-width:360px;padding:14px;font-size:11px}.mf-document--receipt .mf-document-header{display:flex;flex-direction:column;gap:14px;text-align:center;border-bottom:1px dashed #9caea4}.mf-document--receipt .mf-document-identity{text-align:center}.mf-document--receipt h1{font-size:19px}.mf-document--receipt h2{font-size:17px}.mf-document--receipt .mf-document-parties{display:block;margin-bottom:18px}.mf-document--receipt .mf-document-parties>div{margin-bottom:12px}.mf-document--receipt .mf-document-items{font-size:10px}.mf-document--receipt .mf-document-items th{font-size:9px}.mf-document--receipt .mf-document-items :is(td,th):first-child{width:38%}.mf-document--receipt .mf-document-items :is(td,th):nth-child(2){width:12%}.mf-document--receipt .mf-document-totals{display:block}.mf-document--receipt .mf-document-totals dl{min-width:0}.mf-document--receipt .mf-document-total{font-size:14px}.mf-document--receipt .mf-document-qr{margin-inline:auto}.mf-document--receipt .mf-document-notice{font-size:10px}.mf-document.compact{padding:20px;font-size:11px}
@media(max-width:560px){.mf-document-header{gap:12px}.mf-document h1{font-size:23px}.mf-document h2{font-size:16px}.mf-document-parties{grid-template-columns:1fr;gap:16px}.mf-document-items{font-size:10px}.mf-document-items th{font-size:9px}.mf-document-totals dl{min-width:220px}.mf-document--receipt .mf-document-items :is(td,th):first-child{width:38%}}
.mf-document--receipt .mf-document-receipt-items :is(th,td):first-child{width:66%}.mf-document--receipt .mf-document-receipt-items :is(th,td):nth-child(2){width:34%;overflow-wrap:anywhere}.mf-document--receipt .mf-document-receipt-items td small{white-space:normal}
@media print{.mf-document{box-shadow:none;max-width:none}.mf-document-items thead{display:table-header-group}.mf-document-items tr,.mf-document-section,.mf-document-signature{break-inside:avoid}}
</style>
